<div class="container">
	<ul class="breadcrumb">
		<li>
			<a href="/">
				Home
			</a>
		</li>
		<li>
			<a href="/movies/dashboard">
				Movie Mania
			</a>
		</li>
		<li class="active">
			Actors Database
		</li>
	</ul>

	<div class="title">
		<h1 class="page-header">Actors Database</h1>
	</div>

	<div style="position:fixed;bottom:30px;right:75px;border:2px solid black;padding:10px;border-radius:20px;background-color:#0BBFB4;z-index:10">
		<?php foreach($actor_movies_alpha as $alpha => $actor_movies): ?>
			<h5 style="display:inline">
				<a href="<?php echo '#alpha-' . $alpha; ?>" class="smooth-scroll" style="color:white">
					<?php echo $alpha; ?>
				</a>
			</h5>
			&nbsp;
		<?php endforeach; ?>
	</div>

	<div style="margin-bottom:30px">
		<?php foreach($actor_movies_alpha as $alpha => $actor_list): ?>
			<h1 id="<?php echo 'alpha-' . $alpha; ?>" class="page-header">
				<?php echo $alpha; ?> 
				<small>
					(<?php echo count($actor_list); ?>)
				</small>
			</h1>
			<div class="row">
				<?php foreach($actor_list as $actor): ?>
					<div class="col-md-3">
						<a href="<?php echo '/movies/browseMovies?actors[]=' . $actor->id . '&order=year DESC'; ?>" target="_blank">
							<?php echo $actor->name; ?>
						</a>
					</div>
				<?php endforeach; ?>
			</div>
		<?php endforeach; ?>
	</div>

</div>
