<?php
	use app\models\Format;
	use app\models\Language;
?>

<div class="container my-container">
	<ul class="breadcrumb">
		<li>
			<a href="/">
				Home
			</a>
		</li>
		<li>
			<a href="/movies/dashboard">
				Movie Mania
			</a>
		</li>
		<li class="active">
			Add Movie
		</li>
	</ul>
	<form class="form-horizontal add-movie-form add-form" name="add-movie-form" method="POST" action="/movies/addMovie">
		<div class="">
			<div class="title">
				<h2>Add Movie</h2>
				<p>Enter the details for adding a new movie to a database</p>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Name:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Enter the name of the movie
								</span>
								<span class="errorMsg">
				                	Please enter valid name
				                </span>
							</label>
				            <div class="col-md-12">
				                <input type="text" name="movie-name" class="form-control" autocomplete="off" tabindex="1">
				            </div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Size:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Enter the size of the movie in bits (Ex:12,345,678)
								</span>
								<span class="errorMsg">
				                	Please enter valid size
				                </span>
							</label>
				            <div class="col-md-12">
				                <input type="text" name="movie-size" class="form-control" autocomplete="off" tabindex="1">
				            </div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Language:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Select the language of the movie.
								</span>
								<span class="errorMsg">
				                	Please select language
				                </span>
							</label>
				            <div class="col-md-12">
				                <select class="form-control" name="movie-language" tabindex="1">
				                	<option value="default">
				                		-- Select Language --
				                	</option>
									<?php foreach(Language::getAllLanguages() as $language): ?>
										<?php $selected = ((($this->request->hasQuery('language')) && !empty($this->request->getQuery('language')) && ($this->request->getQuery('language') == $language->name)) ? 'selected' : ''); ?>
				                		<option value="<?php echo $language->id; ?>" <?php echo $selected; ?>>
				                			<?php echo $language->name; ?>
				                		</option>
				                	<?php endforeach; ?>
				                </select>
				            </div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Format:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Select the format of the movie.
								</span>
								<span class="errorMsg">
				                	Please select format
				                </span>
							</label>
				            <div class="col-md-12">
				                <select class="form-control" name="movie-format" tabindex="1">
				                	<option value="default">
				                		-- Select Format --
				                	</option>
									<?php foreach(Format::getAllFormats() as $format): ?>
				                		<option value="<?php echo $format->id; ?>">
				                			<?php echo $format->name; ?>
				                		</option>
				                	<?php endforeach; ?>
				                </select>
				            </div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group form-field jsSuggestionWrap">
							<label class="control-label col-md-12">
								<span class="label-title">
									Directors:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Enter the names of the director of the movie
								</span>
								<span class="errorMsg">
									Please select director
								</span>
							</label>
							<div class="col-md-12 dropdown jsCustomDropdown">
								<div class="auto-suggest-input">
									<input class="form-control jsCustomDropdownInput" type="text" autocomplete="off" size="50" tabindex="1" data-type="artist" />
									<ul class="suggestions-list dropdown-menu"></ul>
								</div>
								<div class="picked-item-list" data-type="director"></div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Year of release:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Enter the year of release of the movie
								</span>
								<span class="errorMsg">
				                	Please enter valid year
				                </span>
							</label>
				            <div class="col-md-12">
				                <input type="number" name="movie-year" class="form-control" autocomplete="off" tabindex="1">
				            </div>
						</div>
					</div>
				</div>
				<div class="row jsSuggestionWrap">
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Actors:
								</span>
								<span class="mandatory-label"></span>
								<span class="label-description">
									Enter the name of the actors of the movie
								</span>
								<span class="errorMsg">
									Please select actors
								</span>
							</label>
							<div class="col-md-12 dropdown jsCustomDropdown">
								<div class="auto-suggest-input">
									<input class="form-control jsCustomDropdownInput" type="text" autocomplete="off" size="50" tabindex="1" data-type="artist" />
									<ul class="suggestions-list dropdown-menu"></ul>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6"></div>
					<div class="col-md-12 picked-item-list" data-type="actor"></div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Subtitles:
								</span>
								<span class="label-description">
									Does the movie have subtitles?
								</span>
							</label>
							<div class="col-md-12">
								<div class="radio">
				                	<label class="radio-inline">
				                		<input type="radio" name="movie-subtitles" value="1" tabindex="1">
				                		Yes
				                	</label>
				                	<label class="radio-inline">
				                		<input type="radio" name="movie-subtitles" value="0" tabindex="1" checked>
				                		No
				                	</label>
				                </div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Viewed:
								</span>
								<span class="label-description">
									Is the movie seen by me?
								</span>
							</label>
							<div class="col-md-12">
								<div class="radio">
				                	<label class="radio-inline">
				                		<input type="radio" name="movie-seen" value="1" tabindex="1">
				                		Yes
				                	</label>
				                	<label class="radio-inline">
				                		<input type="radio" name="movie-seen" value="0" tabindex="1" checked>
				                		No
				                	</label>
				                </div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Quality:
								</span>
								<span class="label-description">
									What is the quality of the print of the movie?
								</span>
							</label>
							<div class="col-md-12">
								<div class="radio">
				                	<label class="radio-inline">
				                		<input type="radio" name="movie-quality" value="good" tabindex="1">
				                		Good
				                	</label>
				                	<label class="radio-inline">
				                		<input type="radio" name="movie-quality" value="normal" tabindex="1" checked>
				                		Normal
				                	</label>
				                </div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group form-field">
							<label class="control-label col-md-12">
								<span class="label-title">
									Basename:
								</span>
								<span class="label-description">
									Enter the basename of the movie
								</span>
							</label>
				            <div class="col-md-12">
				                <input type="text" name="movie-basename" class="form-control" autocomplete="off" tabindex="1">
				            </div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="form-group form-field action-btns">
						<div class="col-md-3">
						</div>
						<div class="col-md-3">
							<input type="reset" name="reset" class="form-control btn btn-danger" value="Reset" tabindex="1">
						</div>
						<div class="col-md-3">
							<input type="submit" name="reset" class="form-control btn btn-primary" value="Add Movie" tabindex="1">
						</div>
						<div class="col-md-3">
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

<?php
	$this->partial('shared/addArtistPopup');
?>

<script type="text/javascript">
	$(document).ready(function() {
		$(document).on('submit', 'form[name="add-movie-form"]', function(e) {
			if(!forms.validateForms.isAddMovieFormValid($(this)))
			{
				e.preventDefault();
			}
		});
	});
</script>
