<div class="container">
    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="/">
                    Home
                </a>
            </li>
            <li>
                <a href="/movies/dashboard">
                    Movie Mania
                </a>
            </li>
            <li class="active">
                Deleted Movies
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="title">
            <h1 class="page-header">Deleted Movies</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="col-md-3 col-lg-3 col-xs-6 col-sm-4">
                <p class="movie-count">
                    <strong><?php echo count($movieList); ?></strong> movies
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="movie-list clearfix">
            <?php foreach($movieList as $movie): ?>
                <?php $this->partial('movies/movieCard'); ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $(document).on('click', '.jsShowMovieDetail', function(e) {
            e.preventDefault();
        });
    });
</script>
