<div class="container" style="height:600px">
    <ul class="breadcrumb">
        <li class="active">
            Home
        </li>
    </ul>
    <div class="title">
        <h1>
            Welcome to my new Website
        </h1>
    </div>
    <div class="project-list" id="project-list">
        <h3 class="list-heading">
            Features:
        </h3>
        <div class="project-item row">
            <a href="/movies/dashboard">
                <div class="col-md-3 col-lg-3">
                    Movie Mania
                </div>
            </a>
            <a href="/songs/dashboard">
                <div class="col-md-3 col-lg-3">
                    Audio Box
                </div>
            </a>
            <a href="/index/knowYourDay">
                <div class="col-md-3 col-lg-3">
                    Know Your Day
                </div>
            </a>
        </div>
    </div>
    <br /><br />
    <div class=" other-links" id="other-links">
        <h4>
            Other links:
        </h4>
        <div>
            <ul>
                <li>
                    <a href="/index/phpinfo">
                        PHP info
                    </a>
                </li>
                <li>
                    <a href="/index/get_loaded_extensions">
                        Loaded Extensions
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>