<!-- add artist popup box begins -->
<div class="modal fade" id="add_artist" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <button type="button" class="popup-close" data-dismiss="modal"><i class="glyphicon">&times;</i></button>
        <div class="modal-content" id="add_artist_content">
            <?php $this->partial('shared/addArtistContent'); ?>
        </div>
    </div>
</div>
<!-- add artist popup box ends -->