<div class="add-individual-form">
    <div>
        <h3>Add artist</h3>
    </div>
    <form class="form-horizontal add-form" name="add-artist-form" action="/movies/addArtist" method="POST">
        <div class="form-group form-field">
            <label class="control-label col-sm-3">Name:<span class="mandatory-label"></span> </label>
            <div class="col-sm-8">
                <input type="text" name="name" class="form-control mandatory" autocomplete="off">
                <span class="errorMsg">Please enter valid name</span>
            </div>
        </div>
        <div class="form-group form-field">
            <label class="control-label col-sm-3">Gender:<span class="mandatory-label"></span> </label>
            <div class="col-sm-5">
                <div class="radio mandatory">
                    <label class="radio-inline"><input type="radio" name="gender" value="M">Male</label>
                    <label class="radio-inline"><input type="radio" name="gender" value="F">Female</label>
                </div>
                <span class="errorMsg">Please select valid gender</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-7">
                <input class="btn btn-primary" type="submit" name="submit" value="Add Artist">
            </div>
        </div>
    </form>
</div>