<div class="creator-image">
    <img
        height="100px"
        width="80px"
        alt="creator"
        src="/images/creator.jpg"
    >
</div>
<footer class="main-footer">
    <div class="creator-details">
        <div class="creator-signature">
            <h4>
                Created by
                <a
                    href="#"
                    title="Know about creator"
                >
                    Shreyas
                    <span style="font-size: 1em">
                        &copy;
                    </span>
                </a>
            </h4>
        </div>
    </div>
</footer>

<?php $this->partial('shared/loader'); ?>
