<header class="main-header">
    <nav class="navbar navbar-inverse" style="margin-bottom:initial">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    Hande
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        Movie Mania
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/movies/dashboard">
                                Dashboard
                            </a>
                        </li>
                        <li class="divider">
                        <li>
                            <a href="/movies/actorList">
                                By Actors
                            </a>
                        </li>
                        <li>
                            <a href="/movies/directorList">
                                By Directors
                            </a>
                        </li>
                        <li>
                            <a href="/movies/yearList">
                                By Year
                            </a>
                        </li>
                        <li>
                            <a href="/movies/actorCombinations">
                                Actor Combinations
                            </a>
                        </li>
                        <li>
                            <a href="/movies/deletedMovies">
                                Deleted Movies
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        Audio Box
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/songs/dashboard">
                                By Languages
                            </a>
                        </li>
                        <li>
                            <a href="/songs/singerList">
                                By Singers
                            </a>
                        </li>
                        <li>
                            <a href="/songs/composerList">
                                By Composers
                            </a>
                        </li>
                        <li>
                            <a href="/songs/lyricistList">
                                By Lyricists
                            </a>
                        </li>
                        <li>
                            <a href="/songs/yearList">
                                By Years
                            </a>
                        </li>
                    </ul>
                </li>
                <li><a href="/index/knowYourDay">K Y D</a></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        Let's Duel
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/cards/sources">
                                All Sources
                            </a>
                        </li>
                        <li>
                            <a href="/cards/addSource">
                                Add Source
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
