<?php
/**
 * Author: shreyas.hande
 * Date: 1/23/18
 * Time: 11:43 PM
 */

use app\models\Song;

/** @var Song $song */
?>

<div class="container my-container">
    <ul class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="/songs/dashboard">Audio Box</a></li>
        <li>
            <a href="<?php echo '/songs/browseSongs?language=' . $song->movieLanguageName; ?>">
                <?php echo $song->movieLanguageName . ' Songs Database'; ?>
            </a>
        </li>
        <li class="active">Edit Song</li>
    </ul>
    <form class="form-horizontal add-movie-form edit-form" name="edit-song-form" method="POST" action="/songs/editSong">
        <input type="hidden" name="id" value="<?php echo $song->id; ?>">
        <div class="">
            <div class="title">
                <h2>Edit Song</h2>
                <p>Enter the details for adding a new song to a database</p>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-field">
                            <label class="control-label col-md-12">
								<span class="label-title">
									Name:
								</span>
                                <span class="mandatory-label"></span>
								<span class="label-description">
									Enter the name of the song
								</span>
								<span class="errorMsg">
				                	Please enter valid name
				                </span>
                            </label>
                            <div class="col-md-12">
                                <input type="text" name="name" class="form-control" autocomplete="off" tabindex="1" value="<?php echo $song->name; ?>">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-field">
                            <label class="control-label col-md-12">
								<span class="label-title">
									Size:
								</span>
                                <span class="mandatory-label"></span>
								<span class="label-description">
									Enter the size of the song in bits (Ex:12,345,678)
								</span>
								<span class="errorMsg">
				                	Please enter valid size
				                </span>
                            </label>
                            <div class="col-md-12">
                                <input type="text" name="size" class="form-control" autocomplete="off" tabindex="1" value="<?php echo $song->size; ?>">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-field jsSuggestionWrap">
                            <label class="control-label col-md-12">
								<span class="label-title">
									Movie:
								</span>
                                <span class="mandatory-label"></span>
								<span class="label-description">
									Enter the name of the movie
								</span>
								<span class="errorMsg">
									Please select movie
								</span>
                            </label>
                            <div class="col-md-12 dropdown jsCustomDropdown">
                                <div class="auto-suggest-input">
                                    <input class="form-control jsCustomDropdownInput" type="text" name="" autocomplete="off" size="50" tabindex="1" data-type="movie" />
                                    <ul class="suggestions-list dropdown-menu" id="movie_suggestions"></ul>
                                </div>
                                <div class="picked-item-list" data-type="movie"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-field jsSuggestionWrap">
                            <label class="control-label col-md-12">
								<span class="label-title">
									Singers:
								</span>
                                <span class="mandatory-label"></span>
								<span class="label-description">
									Enter the names of singers
								</span>
								<span class="errorMsg">
									Please select singers
								</span>
                            </label>
                            <div class="col-md-12 dropdown jsCustomDropdown">
                                <div class="auto-suggest-input">
                                    <input class="form-control jsCustomDropdownInput" type="text" name="" autocomplete="off" size="50" tabindex="1" data-type="artist" />
                                    <ul class="suggestions-list dropdown-menu"></ul>
                                </div>
                                <div class="picked-item-list" data-type="singer"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-field jsSuggestionWrap">
                            <label class="control-label col-md-12">
								<span class="label-title">
									Composers:
								</span>
                                <span class="mandatory-label"></span>
								<span class="label-description">
									Enter the names of composers
								</span>
								<span class="errorMsg">
									Please select composers
								</span>
                            </label>
                            <div class="col-md-12 dropdown jsCustomDropdown">
                                <div class="auto-suggest-input">
                                    <input class="form-control jsCustomDropdownInput" type="text" name="" autocomplete="off" size="50" tabindex="1" data-type="artist" />
                                    <ul class="suggestions-list dropdown-menu"></ul>
                                </div>
                                <div class="picked-item-list" data-type="composer"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-field jsSuggestionWrap">
                            <label class="control-label col-md-12">
								<span class="label-title">
									Lyricists:
								</span>
                                <span class="mandatory-label"></span>
								<span class="label-description">
									Enter the names of lyricists
								</span>
								<span class="errorMsg">
									Please select lyricists
								</span>
                            </label>
                            <div class="col-md-12 dropdown jsCustomDropdown">
                                <div class="auto-suggest-input">
                                    <input class="form-control jsCustomDropdownInput" type="text" name="" autocomplete="off" size="50" tabindex="1" data-type="artist" />
                                    <ul class="suggestions-list dropdown-menu"></ul>
                                </div>
                                <div class="picked-item-list" data-type="lyricist"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group form-field action-btns">
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-3">
                            <input type="submit" name="reset" class="form-control btn btn-primary" value="Edit Song" tabindex="1">
                        </div>
                        <div class="col-md-5">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<?php
    $this->partial('shared/addArtistPopup');
?>

<script>
    $(document).ready(function() {

        Suggestions.pickSuggestion('<?php echo $song->movieName; ?>', <?php echo $song->movieId; ?>, 'movie');

        <?php foreach($song->singerIds as $index => $singerId): ?>
            Suggestions.pickSuggestion('<?php echo $song->singerNames[$index]; ?>', '<?php echo $singerId; ?>', 'singer');
        <?php endforeach; ?>

        <?php foreach($song->composerIds as $index => $composerId): ?>
            Suggestions.pickSuggestion('<?php echo $song->composerNames[$index]; ?>', '<?php echo $composerId; ?>', 'composer');
        <?php endforeach; ?>

        <?php foreach($song->lyricistIds as $index => $lyricistId): ?>
            Suggestions.pickSuggestion('<?php echo $song->lyricistNames[$index]; ?>', '<?php echo $lyricistId; ?>', 'lyricist');
        <?php endforeach; ?>

        $(document).on('submit', 'form[name="edit-song-form"]', function(e) {
            if(!forms.validateForms.isAddSongFormValid($(this)))
            {
                e.preventDefault();
            }
        });
    });
</script>
