<div class="modal fade" id="audiobox" role="dialog">
    <div class="modal-dialog ">
        <!-- Modal content-->
        <div class="modal-content song-details">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="title jsSongTitle"></h2>
                <p>
                    <span>
                        <i class="glyphicon glyphicon-headphones"></i>
                        <span class="jsSingers"></span>
                    </span>
                </p>
                <p>
                    <span>
                        <i class="glyphicon glyphicon-music"></i>
                        <span class="jsComposers"></span>
                    </span>
                </p>
                <p>
                    <span>
                        <i class="glyphicon glyphicon-edit"></i>
                        <span class="jsLyricists"></span>
                    </span>
                </p>
            </div>
            <div class="modal-body">
                <img src="">
            </div>
            <div class="modal-footer">
                <div align="center">
                    <audio id="audio" controls src="" type="audio/mpeg">
                    </audio>
                </div>
            </div>
        </div>
    </div>
</div>