<?php

use app\constants\Constants;
use app\helpers\AssetHelper;
use app\models\Song;
    /** @var Song $song */
?>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 movie-card song-card">
    <div class="card">
        <img src="<?php echo AssetHelper::getImage($song->movie->id, Constants::CONTEXT_MOVIE); ?>" class="img-thumbnail" alt="<?php echo $song->movie->name; ?>">
        <div class="card-img-overlay">
            <div class="movie-details">
                <p class="movie-year">
                    <?php echo $song->movie->year; ?>
                </p>
                <p class="movie-size">
                    <?php echo $song->size; ?>
                </p>
            </div>
            <div class="controls">
                <a class="btn btn-primary play-song" href="#audiobox" data-toggle="modal" data-id="<?php echo $song->id; ?>" data-src="<?php echo '/audio/' . $song->movie->language->name . '/' . $song->name . '.mp3'; ?>">
                    <i class="glyphicon glyphicon-play-circle" data-toggle="tooltip" title="Play Song"></i>
                </a>
                <?php if(false): ?>
                <a class="btn btn-warning edit-movie" href="/movies/editMovie?id=2288" target="_blank">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
                <a class="btn btn-danger remove-movie" data-id="2288">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="row">
            <a href="<?php echo '/songs/songDetail?id=' . $song->id; ?>" target="_blank">
                <p class="movie-name">
                    <?php echo $song->name; ?>
                </p>
            </a>
        </div>
    </div>
</div>
