<?php
    use app\constants\Constants;
    use app\enums\cards\ViewMode;
?>

<div class="container">
    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="/">
                    Home
                </a>
            </li>
            <li class="active">
                Browse Cards
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="title">
            <h1 class="page-header">
                Browse Cards
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2 col-lg-2 col-xs-6 col-sm-12 add-movie">
                <a class="btn btn-primary" href="/cards/add" target="_blank">
                    <span class="glyphicon glyphicon-plus"></span>
                    Add Cards
                </a>
            </div>
            <div class="col-md-2 col-lg-2 col-xs-6 col-sm-4">
                <p class="movie-count">
                    <strong class="jsTotalCount">
                        <?php echo $totalCount; ?>
                    </strong>
                    cards
                </p>
            </div>
            <div class="col-md-4 col-lg-3 col-xs-7 col-sm-6">
                <div class="dropdown jsCustomDropdown">
                    <input type="text" name="search" class="form-control mandatory jsCustomDropdownInput" autocomplete="off" placeholder="Search Card" data-type="card" />
                    <ul class="suggestions-list dropdown-menu" id="search_movie_dropdown"></ul>
                </div>
            </div>

            <div class="col-md-2 col-lg-2 col-xs-5 col-sm-2">
                <div class="sort-dropdown dropdown view-mode-dropdown">
                    <button class="btn btn-default pull-right" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-sort-by-attributes"></i>
                        View Mode:
                        <span class="visible-lg sort-display jsViewModeDisplay" data-viewMode="<?php echo $viewMode; ?>">
							<?php echo $viewMode; ?>
						</span>
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <?php foreach(ViewMode::getAllValues() as $viewModeOption): ?>
                            <li class="jsViewMode" data-viewMode="<?php echo $viewModeOption; ?>">
                                <span>
									<?php echo $viewModeOption; ?>
								</span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-lg-3 col-xs-5 col-sm-2">
                <?php
                $sortAttributes = array_filter(Constants::getCardAttributes(), function($attribute) {
                    return (isset($attribute['isSortEnabled']) && !empty($attribute['isSortEnabled']));
                });
                $orderArray = [2, 1, 3, 4, 5];
                array_multisort($orderArray, $sortAttributes);

                $currentSortType = array_keys($sortMap)[0];
                $currentSortOrder = $sortMap[$currentSortType];
                $currentSortText = $sortAttributes[$currentSortType]['sortLabel'] . ' ' . $currentSortOrder;
                ?>
                <div class="sort-dropdown dropdown">
                    <button class="btn btn-default pull-right" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-sort-by-attributes"></i>
                        Sort By:
                        <span class="visible-lg sort-display jsSortDisplay" data-sortType="<?php echo $currentSortType; ?>" data-sortOrder="<?php echo $currentSortOrder; ?>">
							<?php echo $currentSortText; ?>
						</span>
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <?php foreach($sortAttributes as $sortType => $attribute): ?>
                            <li>
                                <?php $sortOrders = [
                                    'ASC' => 'glyphicon glyphicon-chevron-up',
                                    'DESC' => 'glyphicon glyphicon-chevron-down'
                                ]; ?>
                                <span class="col-md-6 jsSortLabel">
									<?php echo $attribute['sortLabel']; ?>
								</span>
                                <?php foreach($sortOrders as $sortOrder => $arrowClass): ?>
                                    <a href="javascript:void(0);" class="col-md-3 jsSort" data-sortType="<?php echo $sortType; ?>" data-sortOrder="<?php echo $sortOrder; ?>">
                                        <i class="<?php echo $arrowClass; ?>"></i>
                                    </a>
                                <?php endforeach; ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="row">
                <?php
                    $filterClass = (($viewMode !== ViewMode::DEFAULT) ? 'hidden' : 'col-md-3');
                    $cardListClass = (($viewMode !== ViewMode::DEFAULT) ? 'col-md-12' : 'col-md-9');
                ?>
                <div class="<?php echo $filterClass; ?>">
                    <?php $this->partial('shared/filters/filters', ['filtersForDisplay' => Constants::getCardAttributes()]); ?>
                </div>
                <div class="<?php echo $cardListClass; ?>">
                    <div class="row movie-list clearfix jsMovieContainer">
                        <?php foreach($cardList as $card): ?>
                            <?php $this->partial('cards/card', [
                                    'card' => $card,
                                    'isRarityRequired' => true,
                                    'viewMode' => $viewMode
                            ]); ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->partial('cards/obtainModal'); ?>

<?php $this->partial('cards/versionModal'); ?>

<script>
    var offset = <?php echo $offset; ?>;
    var totalCount = <?php echo $totalCount; ?>;

    $(document).ready(function() {
        <?php if(isset($filterValues['sources']['values']) && !empty($filterValues['sources']['values'])): ?>
            <?php foreach($filterValues['sources']['values'] as $index => $source): ?>
                Suggestions.pickSuggestion('<?php echo $source["name"]; ?>', '<?php echo $source["id"]; ?>', 'source');
            <?php endforeach; ?>
        <?php endif; ?>
    });
</script>
