<?php

use app\constants\Constants;
use app\helpers\AssetHelper;
use app\models\Card;

/** @var Card $card */

$overlayClass = 'card-img-overlay' . (($isRarityRequired) ? ' with-rarity' : '');
$foilTypeClass = (((isset($myCard) && !empty($myCard))) ? ' ' . strtolower($myCard->cardGlossType) : '');
$myCardClass = (((isset($myCard) && !empty($myCard))) ? ' my-card' : '');

$cardClass = ((isset($myCard) && !empty($myCard)) ? '' : 'col-md-4 col-sm-4 col-xs-12 col-lg-3') . ' movie-card jsCard duel-links' . $foilTypeClass . $myCardClass;

?>
<div class="<?php echo $cardClass; ?>" data-id="<?php echo $card->id; ?>">
    <?php if($isRarityRequired): ?>
        <div class="<?php echo 'card-rarity ' . strtolower($card->rarity); ?>">
            <?php

                $rarityName = $card->rarity;
                $rarityParts = explode('_', $rarityName);

                $rarityDisplayParts = [];
                foreach($rarityParts as $rarityPart)
                {
                    $rarityDisplayParts[] = strtoupper($rarityPart[0]);
                }
                echo implode('', $rarityDisplayParts);
            ?>
        </div>
    <?php endif; ?>
    <div class="card">
        <img src="<?php echo $card->imageUrl; ?>" class="img-thumbnail" alt="<?php echo $card->name; ?>">
        <div class="<?php echo $overlayClass; ?>">
            <div class="controls">
                <?php $this->partial('cards/actionButtons'); ?>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="row">
            <a href="<?php echo '/cards/detail?id=' . $card->id; ?>" target="_blank" class="jsShowMovieDetail">
                <p class="movie-name">
                    <?php echo $card->name; ?>
                </p>
            </a>
        </div>
    </div>
</div>