<?php

use app\constants\Constants;
use app\enums\cards\ViewMode;
use app\helpers\AssetHelper;
use app\models\Card;

/** @var Card $card */

$overlayClass = 'card-img-overlay' . (($isRarityRequired) ? ' with-rarity' : '');
$foilTypeClass = (((isset($myCard) && !empty($myCard))) ? ' ' . strtolower($myCard->cardGlossType) : '');
$myCardClass = (((isset($myCard) && !empty($myCard))) ? ' my-card' : '');
$gridClass = ((ViewMode::DEFAULT !== $viewMode) ? ((ViewMode::SMALL === $viewMode) ? ' col-md-1-10' : ' col-md-2') : ' col-md-3');
$viewModeClass = ((ViewMode::DEFAULT !== $viewMode) ? ((ViewMode::SMALL === $viewMode) ? ' view-mode-small' : ' view-mode') : '');

$cardClass = 'movie-card jsCard duel-links' . $gridClass . $foilTypeClass . $myCardClass . $viewModeClass;

?>
<div class="<?php echo $cardClass; ?>" data-id="<?php echo $card->id; ?>">
    <?php if($isRarityRequired): ?>
        <div class="<?php echo 'card-rarity ' . strtolower($card->rarity); ?>">
            <?php

                $rarityName = $card->rarity;
                $rarityParts = explode('_', $rarityName);

                $rarityDisplayParts = [];
                foreach($rarityParts as $rarityPart)
                {
                    $rarityDisplayParts[] = strtoupper($rarityPart[0]);
                }
                echo implode('', $rarityDisplayParts);
            ?>
        </div>
    <?php endif; ?>
    <div class="card">
        <?php for($i = 0; $i < 70; $i++): ?>
        <i></i>
        <?php endfor; ?>
        <img src="<?php echo $card->imageUrl; ?>" class="img-thumbnail" alt="<?php echo $card->name; ?>">
        <div class="<?php echo $overlayClass; ?>">
            <div class="controls">
                <?php $this->partial('cards/actionButtons'); ?>
            </div>
        </div>

        <?php if(property_exists($card, 'glossTypeStats')): ?>
            <?php
            $stats = json_decode($card->glossTypeStats, true);
            $order = [
                'PRISMATIC',
                'GLOSSY',
                'NORMAL'
            ];

            $foilTypeText = '';

            foreach($order as $index => $key)
            {
                if($index > 0)
                {
                    $foilTypeText .= '/';
                }

                $foilTypeText .= '<span class="' . $key .'">' . $stats[$key] . '</span>';
            }
            ?>
            <p class="foil-type-stats"><?php echo $foilTypeText; ?></p>
        <?php endif; ?>
    </div>
    <div class="col-md-12">
        <div class="row">
            <a href="<?php echo '/cards/detail?id=' . $card->id; ?>" target="_blank" class="jsShowMovieDetail">
                <p class="movie-name">
                    <?php echo $card->name; ?>
                </p>
            </a>
        </div>
    </div>
</div>