<!-- obtain card popup box begins -->
<div class="modal fade" id="obtain_card" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <button type="button" class="popup-close" data-dismiss="modal"><i class="glyphicon">&times;</i></button>
        <div class="modal-content" id="obtain_card_content">
            <?php $this->partial('cards/obtain'); ?>
        </div>
    </div>
</div>
<!-- obtain card popup box ends -->