<?php

?>
<div class="add-individual-form">
    <div>
        <h3>Add Version</h3>
    </div>
    <form class="form-horizontal add-form" name="add-version-form" action="/cards/version" method="POST" enctype="multipart/form-data">
        <input
            type="hidden"
            name="cardName"
        >

        <input
            type="hidden"
            name="cardId"
        >
        <div class="form-group form-field">
            <div class="col-sm-3"></div>
            <div class="col-sm-8">
                <input
                        name="image"
                        type="hidden"
                        value=""
                />
                <div class="col-md-12">
                    <?php $this->partial('shared/fileUpload', [
                        'name' => 'image',
                        'id' => 'imageUpload',
                        'label' => 'Cover Image',
                        'description' => 'Enter the image for the card',
                        'uploadText' => 'Upload',
                        'errorMsg' => 'Image should be of .jpg with max size 300kb.',
                        'maxFileSize' => (300 * 1024 * 1024),
                        'allowedExtensions' => 'jpg',
                        'fileName' => ''
                    ]); ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-7">
                <input class="btn btn-primary" type="submit" name="submit" value="Add">
            </div>
        </div>
    </form>
</div>