<?php
    use app\helpers\AssetHelper;
    use app\models\Movie;
    use app\utils\CommonUtils;

    /** @var Movie $movie */
?>
<?php if(count($related_movies) > 0): ?>
	<?php foreach($related_movies as $movie): ?>
		<?php
			if($this->request->hasQuery('context') && !empty($this->request->getQuery('context')))
			{
				$href = "javascript:Suggestions.pickSuggestion('" . CommonUtils::formatStringWithEscapeChars($movie->name) . "'," . $movie->id . ", 'movie')";
				$target = '';
			}
			else
			{
				$href = "/movies/movieDetail?id=" . $movie->id;
				$target = '_blank';
			}
		?>
		<li>
			<a href="<?php echo $href; ?>" target="<?php echo $target; ?>">
				<img class="hidden-xs" src="<?php echo $movie->imageUrl; ?>" width="50" height="75" alt="<?php echo $movie->name;?>">
				<?php echo $movie->name; ?>
			</a>
		</li>
	<?php endforeach; ?>
<?php else: ?>
	<p style="padding: 5px">No results</p>
<?php endif; ?>
